### ISSUE TITLE
Failed to execute script 'glljobstat' due to unhandled exception! | Worked with MDS but not with OSS

### ISSUE THREAD

**Issue by alexandrestein** [DDNeu/global-lustre-jobstats#3]
I'm using a complied/portable version of the script. (complied with PyInstaller) 
[glljobstat.zip](https://github.com/user-attachments/files/17590586/glljobstat.zip)

I'm running the tool in a customer environment where we can't install Python dependencies. 
I was able to use the tool without issues for the MDS (12 systems).
But when I tried to collect 12 OSS I got that error:
```
ddn@par2-ai-prd-s1bastion01:~/jobstats$ ./glljobstat -v
Traceback (most recent call last):
  File "glljobstat.py", line 1153, in <module>
  File "glljobstat.py", line 1135, in Run
  File "glljobstat.py", line 969, in run_once_retry
    stdin, stdout, stderr = ssh.exec_command(cmd)
  File "glljobstat.py", line 922, in run_once_par
    return self.run_once_par(query_type)
  File "glljobstat.py", line 630, in merge_job
    if not any(val != 0 and isinstance(val, int) for val in job.values()):
KeyError: 'hist'
[PYI-1225883:ERROR] Failed to execute script 'glljobstat' due to unhandled exception!
```

I tried to add the 12 MDS servers but did not help. 
I haven't looked to carefully into the source code but maybe you have a good idea why this is.

**Can you please help?**

**Comment by bolausson** [comment]
New Lustre releases introduced an additional field "hist" in the jobstats - a IO size histogram for OSS:

```
# lctl get_param obdfilter.*.job_stats
[...]
- job_id:          "121312:422311:node02"
  snapshot_time:   1730401348.468336243 secs.nsecs
  start_time:      1730401289.557517083 secs.nsecs
  elapsed_time:    58.910819160 secs.nsecs
  read_bytes:      { samples:          47, unit: bytes, min:     4096, max:  1036288, sum:          4595712, sumsq:      2822464602112, hist: { 4K: 29, 64K: 10, 128K: 1, 256K: 2, 512K: 1, 1M: 4 } }
  write_bytes:     { samples:           0, unit: bytes, min:        0, max:        0, sum:                0, sumsq:                  0, hist: {  } }
  read:            { samples:          47, unit: usecs, min:       65, max:    23616, sum:           209452, sumsq:         2346868576 }
  write:           { samples:           0, unit: usecs, min:        0, max:        0, sum:                0, sumsq:                  0 }
  getattr:         { samples:           0, unit: usecs, min:        0, max:        0, sum:                0, sumsq:                  0 }
  setattr:         { samples:           0, unit: usecs, min:        0, max:        0, sum:                0, sumsq:                  0 }
  punch:           { samples:           0, unit: usecs, min:        0, max:        0, sum:                0, sumsq:                  0 }
  sync:            { samples:           0, unit: usecs, min:        0, max:        0, sum:                0, sumsq:                  0 }
  destroy:         { samples:           0, unit: usecs, min:        0, max:        0, sum:                0, sumsq:                  0 }
  create:          { samples:           0, unit: usecs, min:        0, max:        0, sum:                0, sumsq:                  0 }
  statfs:          { samples:           0, unit: usecs, min:        0, max:        0, sum:                0, sumsq:                  0 }
  get_info:        { samples:           0, unit: usecs, min:        0, max:        0, sum:                0, sumsq:                  0 }
  set_info:        { samples:           0, unit: usecs, min:        0, max:        0, sum:                0, sumsq:                  0 }
  quotactl:        { samples:           0, unit: usecs, min:        0, max:        0, sum:                0, sumsq:                  0 }
  prealloc:        { samples:           0, unit: usecs, min:        0, max:        0, sum:                0, sumsq:                  0 }
[...]
```

This is not yet implemented for all possible operational modes of global-lustre-jobstats.py

You can disable this field by using "-nh" (introduced in https://github.com/DDNeu/global-lustre-jobstats/commit/9a56a8a0a1bd19950dbc6103a738a112c38e2d74 on 19. October 2024)
https://github.com/DDNeu/global-lustre-jobstats/blob/9a56a8a0a1bd19950dbc6103a738a112c38e2d74/glljobstat.py#L131

This effectively removes the "history" key/value from the dictionary and thus should make it work as usual:
https://github.com/DDNeu/global-lustre-jobstats/blob/9a56a8a0a1bd19950dbc6103a738a112c38e2d74/glljobstat.py#L1111

Let me know if this helps.

**Comment by alexandrestein** [comment]
Hello @bolausson,

Please excuse me for the late reply.
It worked, adding the `-nh` resolved it.

Thanks a lot for your quick and great help :smile:

**Comment by bolausson** [comment]
You made me think - I will invert this.
As long as the "histogram" is not fully implemented, it should be disabled by default and e.g. "-eh" (--enable-histo) should turn it on.

(I'll do that as soon as the lab is back online)
